import {useCallback,useEffect,useState} from 'react';
import {Check,Copy,Lock,RefreshCw,Trash2,Users} from 'lucide-react';
import {callupRequest,confirmationMessage,copyCallupText,type Callup} from './callups';
import './callups.css';
interface LegacyJourney {id:string;createdAt:string;message:string;attendanceId?:string;data:{fecha:string}}
export default function ConvocatoriasPanel({journeys,onOpenLegacy,onDeleted}:{journeys:LegacyJourney[];onOpenLegacy:(id:string)=>void;onDeleted:(id:string)=>void}){
 const [items,setItems]=useState<Callup[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[confirmClose,setConfirmClose]=useState(false),[confirmDelete,setConfirmDelete]=useState(false);
 const refresh=useCallback(async()=>{try{const data=await callupRequest<{callups:Callup[]}>();setItems(data.callups);setError('');setLoaded(true);}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},10000);return()=>clearInterval(timer);},[refresh]);
 const current=items.find(c=>c.id===selected);
 const historical=journeys.filter(j=>!j.attendanceId);
 const copy=async(c:Callup)=>{try{await copyCallupText(confirmationMessage(c.message,location.origin+'/e/'+c.token,c.prompt));setNotice('Mensaje copiado con el enlace de confirmación.');}catch(e){setError((e as Error).message);}};
 return <div className="callups-workspace">
 <div className="callups-toolbar"><p>Las respuestas se actualizan automáticamente. Solo tú puedes cerrar una convocatoria.</p><button className="secondary-button" onClick={()=>void refresh()} aria-label="Actualizar respuestas"><RefreshCw size={16}/> Actualizar</button></div>
 {error&&<p role="alert" className="callups-error">{error}</p>}{notice&&<p role="status" className="callups-success">{notice}</p>}
 {!loaded&&!error&&<p role="status">Cargando convocatorias…</p>}
 {current?<section className="callups-card">
 <button className="secondary-button" onClick={()=>{setSelected('');setConfirmClose(false);setConfirmDelete(false);}}>Volver a convocatorias</button>
 <div className="callups-title"><div><span className="eyebrow">{current.closed?'CERRADA':'ABIERTA'}</span><h2>{current.title}</h2><p>{current.match_date.split('-').reverse().join('/')} · {current.match_time} · {current.field}</p></div><Users size={24}/></div>
 <div className="callups-counts">{(['SI','NO','PENDIENTE'] as const).map(state=><div key={state} className={'count-'+state}><strong>{current.players.filter(p=>p.estado===state).length}</strong><span>{state==='SI'?'Sí van':state==='NO'?'No pueden':'Pendientes'}</span></div>)}</div>
 <ul className="callups-roster">{current.players.map(p=><li key={p.jugador_id} className={`response-${p.estado}`}><span className="callups-number">{p.dorsal||'—'}</span><div className="callups-player"><strong>{p.nombre}</strong><span>{p.estado==='SI'?'✅ Sí va':p.estado==='NO'?'No puede asistir':'Pendiente'}</span>{p.estado==='NO'&&p.motivo&&<p>{p.motivo}</p>}<small>{p.updated_at?'Última respuesta: '+new Date(p.updated_at).toLocaleString('es-ES',{timeZone:'Europe/Madrid'}):'Sin respuesta'}</small></div></li>)}</ul>
 {!current.players.length&&<p>No hay jugadores en esta convocatoria.</p>}
<div className="callups-actions"><button className="primary-button" onClick={()=>void copy(current)}><Copy size={16}/> Copiar WhatsApp con enlace</button>{!current.closed&&<button className="secondary-button" onClick={()=>setConfirmClose(true)}><Lock size={16}/> Cerrar convocatoria</button>}{current.closed&&<button className="secondary-button" onClick={()=>setConfirmDelete(true)}><Trash2 size={16}/> Eliminar convocatoria</button>}</div>
  {confirmClose&&!current.closed&&<div className="callups-close"><p>¿Cerrar esta convocatoria? Se conservarán las respuestas y el enlace dejará de aceptar cambios.</p><button className="primary-button" disabled={busy} onClick={async()=>{setBusy(true);try{await callupRequest({action:'close',id:current.id});await refresh();setConfirmClose(false);setNotice('Convocatoria cerrada.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Cerrando…':'Confirmar cierre'}</button><button className="secondary-button" disabled={busy} onClick={()=>setConfirmClose(false)}>Cancelar</button></div>}
  {confirmDelete&&current.closed&&<div className="callups-close"><p>¿Eliminar esta convocatoria cerrada? Se borrarán sus respuestas de forma permanente.</p><button className="primary-button" disabled={busy} onClick={async()=>{setBusy(true);try{await callupRequest({action:'delete',id:current.id});onDeleted(current.id);await refresh();setSelected('');setConfirmDelete(false);setNotice('Convocatoria eliminada.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Eliminando…':'Eliminar definitivamente'}</button><button className="secondary-button" disabled={busy} onClick={()=>setConfirmDelete(false)}>Cancelar</button></div>}
 </section>:<>
 {(['Abiertas','Cerradas'] as const).map(group=><section key={group} className={`callups-card callups-group ${group==='Abiertas'?'is-open':'is-closed'}`}><h2>{group}</h2><div className="callups-list">{items.filter(c=>c.closed===(group==='Cerradas')).map(c=><button key={c.id} onClick={()=>{setSelected(c.id);setNotice('');}}><div><strong>{c.title}</strong><small>{c.match_date.split('-').reverse().join('/')} · {c.match_time}</small><span>{c.players.filter(p=>p.estado==='SI').length} sí · {c.players.filter(p=>p.estado==='NO').length} no · {c.players.filter(p=>p.estado==='PENDIENTE').length} pendientes</span></div>{c.closed?<Lock size={18}/>:<Check size={18}/>}</button>)}</div>{loaded&&!items.some(c=>c.closed===(group==='Cerradas'))&&<p className="callups-empty">{group==='Abiertas'?'No hay convocatorias abiertas. Abre un partido de la Agenda y comparte su citación.':'Todavía no hay convocatorias cerradas.'}</p>}</section>)}
 {historical.length>0&&<section className="callups-card"><h2>Mensajes anteriores</h2><p>Mensajes guardados antes de activar confirmaciones. Se conserva su contenido original.</p><div className="callups-list">{historical.map(j=><button key={j.id} onClick={()=>onOpenLegacy(j.id)}><div><strong>{j.message.split('\n')[0].replace(/\*/g,'')}</strong><small>{j.data.fecha||new Date(j.createdAt).toLocaleDateString('es-ES')}</small><span>Consultar mensaje guardado</span></div></button>)}</div>{!historical.length&&<p className="callups-empty">No hay mensajes anteriores guardados.</p>}</section>}
 </>}
 </div>;
}
