import { useEffect, useState } from 'react';
import './economy.css';
import { EnrollmentPanel } from './EnrollmentPanel';

type Data={settings:{scope:string;rate:number}[];clubs:{id:string;nombre:string}[];campaigns:{id:string;name:string;club_name:string;total_cents:number;fee_bps:number;installments:{date:string;amount:number}[]}[]};
const euros=(c:number)=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(c/100);
const cents=(s:string)=>Math.round(Number(s)*100);
async function request(body?:unknown,previewClub?:string):Promise<Data>{const r=await fetch('/api/clubs?section=economy'+(previewClub?'&previewClub='+encodeURIComponent(previewClub):''),{method:body?'POST':'GET',credentials:'include',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error||'No se pudo guardar.');return data}
export function EconomyPanel(props:{global:boolean;previewClub?:string}){
 return props.global ? <LegacyEconomyPanel {...props}/> : <EnrollmentPanel clubId={props.previewClub}/>;
}
function LegacyEconomyPanel({global,previewClub}:{global:boolean;previewClub?:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [campaignClub,setCampaignClub]=useState('');
 const [scope,setScope]=useState('global'),[rate,setRate]=useState('3'),[total,setTotal]=useState('340'),[vat,setVat]=useState('21'),[processor,setProcessor]=useState('0'),[fixed,setFixed]=useState('0');
 const [name,setName]=useState(''),[parts,setParts]=useState([{date:'',amount:'340'}]);
 useEffect(()=>{let active=true;setData(null);setError('');setMessage('');setName('');setTotal('340');setParts([{date:'',amount:'340'}]);request(undefined,previewClub).then(d=>{if(active){setData(d);setRate(String((d.settings.find(s=>s.scope==='global')?.rate??300)/100))}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[previewClub]);
 const save=async(body:unknown)=>{setBusy(true);setError('');setMessage('');try{setData(await request(body,previewClub));setMessage('Configuración guardada.');}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setBusy(false)}};
 const baseRate=data?.settings.find(s=>s.scope==='global')?.rate??300;
 const chosenRate=global?Math.round(Number(rate)*100):(data?.settings.find(s=>s.scope===data.clubs[0]?.id)?.rate??baseRate);
 const principal=cents(total),fee=Math.round(principal*chosenRate/10000),tax=Math.round(fee*Number(vat)/100),family=principal+fee+tax;
 const cost=Math.round(family*Number(processor)/100)+cents(fixed)*parts.length;
 return <section className="economy-panel" aria-label="Gestión económica"><header><span>GESTIÓN ECONÓMICA</span><h2>{global?'Comisiones y campañas de los clubes':'Cuotas de temporada'}</h2><p>Configuración y simulación. Los cobros y las inscripciones todavía no están activados.</p></header>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {!data?<p>Cargando configuración…</p>:<>
 {global&&<form onSubmit={e=>{e.preventDefault();void save({action:'commission',club_id:scope==='global'?null:scope,rate:Math.round(Number(rate)*100)})}}><h3>Comisión de Convo</h3><label>Aplicar a<select value={scope} onChange={e=>{const id=e.target.value;setScope(id);setRate(String((data.settings.find(s=>s.scope===id)?.rate??baseRate)/100));setMessage('')}}><option value="global">Comisión general</option>{data.clubs.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label>Comisión (%)<input type="number" min="0" max="100" step="0.01" required value={rate} onChange={e=>setRate(e.target.value)}/></label><p>{scope==='global'?'Se aplica a los clubes sin porcentaje propio.':data.settings.some(s=>s.scope===scope)?'Este club tiene una comisión específica.':'Este club utiliza actualmente la comisión general.'} Las campañas guardadas conservan su porcentaje.</p><div><button disabled={busy}>Guardar comisión</button>{scope!=='global'&&<button type="button" disabled={busy} onClick={()=>{setRate(String(baseRate/100));void save({action:'commission',club_id:scope,rate:null})}}>Usar comisión general</button>}</div></form>}
 <form onSubmit={e=>{e.preventDefault();if(!global)void save({action:'campaign',name,total_cents:principal,installments:parts.map(p=>({date:p.date,amount:cents(p.amount)}))})}}><h3>{global?'Simulador de ingresos':'Crear campaña'}</h3>
 {!global&&<label>Nombre de la campaña<input required maxLength={120} placeholder="Temporada 2026–2027" value={name} onChange={e=>setName(e.target.value)}/></label>}
 <label>Cuota íntegra para el club (€)<input type="number" min="0.01" max="100000" step="0.01" required value={total} onChange={e=>setTotal(e.target.value)}/></label>
 {!global&&<><h4>Plazos de la cuota del club</h4><p>Introduce importes que sumen la cuota total, con fechas en orden. Para pago único, deja un solo plazo.</p>{parts.map((p,i)=><div className="economy-part" key={i}><label>Fecha del plazo {i+1}<input type="date" required value={p.date} onChange={e=>setParts(parts.map((x,j)=>j===i?{...x,date:e.target.value}:x))}/></label><label>Importe (€)<input type="number" min="0.01" step="0.01" required value={p.amount} onChange={e=>setParts(parts.map((x,j)=>j===i?{...x,amount:e.target.value}:x))}/></label>{parts.length>1&&<button type="button" onClick={()=>setParts(parts.filter((_,j)=>j!==i))}>Quitar plazo</button>}</div>)}<button type="button" disabled={parts.length>=24} onClick={()=>setParts([...parts,{date:'',amount:''}])}>Añadir plazo</button><p>Total de plazos: {euros(parts.reduce((n,p)=>n+cents(p.amount),0))} / {euros(principal)}</p></>}
 {global&&<><label>Número de plazos por inscripción<input type="number" min="1" max="24" value={parts.length} onChange={e=>setParts(Array.from({length:Math.max(1,Math.min(24,Number(e.target.value)||1))},()=>({date:'',amount:''})))}/></label><label>IVA del servicio para simular (%)<input type="number" min="0" max="100" step="0.01" value={vat} onChange={e=>setVat(e.target.value)}/></label><label>Coste estimado de plataforma (%)<input type="number" min="0" max="100" step="0.01" value={processor} onChange={e=>setProcessor(e.target.value)}/></label><label>Coste fijo por cobro (€)<input type="number" min="0" step="0.01" value={fixed} onChange={e=>setFixed(e.target.value)}/></label></>}
 <dl><dt>Para el club</dt><dd>{euros(principal)}</dd><dt>Comisión Convo ({chosenRate/100} %)</dt><dd>{euros(fee)}</dd><dt>IVA estimado sobre la comisión ({vat} %)</dt><dd>{euros(tax)}</dd><dt>Total estimado para la familia</dt><dd>{euros(family)}</dd>{global&&<><dt>Costes estimados del procesador</dt><dd>{euros(cost)}</dd><dt>Margen estimado de Convo, sin IVA</dt><dd>{euros(fee-cost)}</dd></>}</dl><p>Simulación orientativa: IVA pendiente de confirmación fiscal. {global?'Introduce las tarifas del proveedor; cero no significa que el procesamiento sea gratuito. El margen excluye otros gastos, devoluciones e impuestos.':'La campaña guarda su cuota, plazos y comisión; todavía no ofrece contratación ni cobros.'}</p>
 {!global&&<button disabled={busy}>Guardar campaña</button>}</form>
 <div><h3>Campañas guardadas</h3>{!data.campaigns.length&&<p>Todavía no hay campañas.</p>}{data.campaigns.map(c=><article key={c.id}><h4>{c.name}</h4>{global&&<p>{c.club_name}</p>}<p>Cuota del club: {euros(c.total_cents)} · Comisión guardada: {c.fee_bps/100} %</p><ul>{c.installments.map((p,i)=><li key={i}>{p.date.split('-').reverse().join('/')} — {euros(p.amount)}</li>)}</ul><small>Configurada · Inscripciones y cobros desactivados</small></article>)}</div>
 {global&&<div><h3>Preparar campañas de un club</h3><label>Club<select value={campaignClub} onChange={e=>setCampaignClub(e.target.value)}><option value="">Selecciona un club</option>{data.clubs.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label>{campaignClub&&<div key={campaignClub}><EconomyPanel global={false} previewClub={campaignClub}/></div>}</div>}
 {global&&<div><h3>Control de cobros</h3><p>Los cobros por club, pendientes y liquidaciones estarán disponibles cuando se conecte la plataforma de pago.</p><button disabled>Cobros por club</button> <button disabled>Liquidaciones</button></div>}
 </>}
 </section>
}
