import { useEffect, useState } from 'react';
import './economy.css';
import './enrollment.css';
import { EnrollmentPanel } from './EnrollmentPanel';

type ProviderStatus={payments:boolean;email:boolean;ready:boolean};
type ClubStatus={id:string;nombre:string;slug:string;providers:ProviderStatus;campaign:{name:string;total_cents:number;published:boolean;payment_required:boolean}|null;confirmed:number;pending:number;adminId:string};
type Data={settings:{scope:string;rate:number}[];clubs:{id:string;nombre:string}[];campaigns:unknown[];clubStatus:ClubStatus[]};
const euros=(c:number)=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(c/100);
const cents=(s:string)=>Math.round(Number(s)*100);
async function request(body?:unknown,previewClub?:string):Promise<Data>{const r=await fetch('/api/clubs?section=economy'+(previewClub?'&previewClub='+encodeURIComponent(previewClub):''),{method:body?'POST':'GET',credentials:'include',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error||'No se pudo guardar.');return data}
export function EconomyPanel(props:{global:boolean;previewClub?:string;onImpersonate?: (accountId:string)=>Promise<void>}){
 return props.global ? <PlatformFinance {...props}/> : <EnrollmentPanel clubId={props.previewClub}/>;
}
function PlatformFinance({onImpersonate}:{onImpersonate?: (accountId:string)=>Promise<void>}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[entering,setEntering]=useState('');
 const [scope,setScope]=useState('global'),[rate,setRate]=useState('3');
 const [clubFocus,setClubFocus]=useState('');
 useEffect(()=>{let active=true;request().then(d=>{if(active){setData(d);setRate(String((d.settings.find(s=>s.scope==='global')?.rate??300)/100))}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 const save=async(body:unknown)=>{setBusy(true);setError('');setMessage('');try{setData(await request(body));setMessage('Configuración guardada.');}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setBusy(false)}};
 const enterAsAdmin=async(club:ClubStatus)=>{if(!club.adminId||entering)return;setEntering(club.id);setError('');setMessage('');try{if(onImpersonate)await onImpersonate(club.adminId)}catch(e){setError(e instanceof Error?e.message:'No se pudo entrar en el club.')}finally{setEntering('')}};
 if(clubFocus){const club=data?.clubStatus.find(c=>c.id===clubFocus);return <section className="economy-panel"><div className="platform-preview-bar"><button onClick={()=>setClubFocus('')}>← Volver a finanzas</button><div><span>VISTA DEL CLUB · {club?.nombre||''}</span><small>Modo superadmin: puedes revisar y editar la gestión de {club?.nombre||'este club'}, igual que su administrador.</small></div></div><EnrollmentPanel clubId={clubFocus}/></section>}
 return <section className="economy-panel" aria-label="Finanzas y estado por club"><header><span>SUPERADMINISTRACIÓN · FINANZAS</span><h2>Comisiones y estado por club</h2><p>Control de la plataforma. La gestión de cada club (temporadas, inscripciones y cuotas) vive en su propio panel.</p></header>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {!data?<p>Cargando finanzas…</p>:<>
 <form className="economy-card" onSubmit={e=>{e.preventDefault();void save({action:'commission',club_id:scope==='global'?null:scope,rate:Math.round(Number(rate)*100)})}}><h3>Comisión de Convo</h3><label>Aplicar a<select value={scope} onChange={e=>{const id=e.target.value;setScope(id);setRate(String((data.settings.find(s=>s.scope===id)?.rate??data.settings.find(s=>s.scope==='global')?.rate??300)/100));setMessage('')}}><option value="global">Comisión general</option>{data.clubs.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label>Comisión (%)<input type="number" min="0" max="100" step="0.01" required value={rate} onChange={e=>setRate(e.target.value)}/></label><p>{scope==='global'?'Se aplica a los clubes sin porcentaje propio.':data.settings.some(s=>s.scope===scope)?'Este club tiene una comisión específica.':'Este club utiliza actualmente la comisión general.'}</p><div><button disabled={busy}>Guardar comisión</button>{scope!=='global'&&<button type="button" disabled={busy} onClick={()=>{setRate(String((data.settings.find(s=>s.scope==='global')?.rate??300)/100));void save({action:'commission',club_id:scope,rate:null})}}>Usar comisión general</button>}</div></form>
 <div className="economy-card"><header><div><h3>Estado por club</h3></div><span>{data.clubStatus.filter(c=>c.campaign?.published&&c.providers.ready).length}/{data.clubStatus.length} operativos</span></header><div className="platform-club-grid">{data.clubStatus.map(c=><article className="platform-club-card" key={c.id}><header><h3>{c.nombre}</h3><span className={`enrollment-badge ${c.providers.ready?'success':''}`}>{c.providers.ready?'Activo':'Pendiente'}</span></header><div className="platform-chips"><span className={c.providers.payments?'ok':''}>Pasarela {c.providers.payments?'conectada':'pendiente'}</span><span className={c.providers.email?'ok':''}>Correo {c.providers.email?'conectado':'pendiente'}</span>{c.campaign?<span className={c.campaign.published?'ok':''}>Temporada {c.campaign.published?'abierta':'cerrada'}</span>:<span>Sin temporada</span>}{c.campaign&&c.campaign.payment_required===false&&<span className="ok">Sin pago</span>}</div>{c.campaign&&<p className="platform-campaign">{c.campaign.name} · {euros(c.campaign.total_cents)}</p>}<p className="platform-counts"><strong>{c.confirmed}</strong> inscripciones confirmadas · <strong>{c.pending}</strong> pendientes</p><footer><button disabled={!c.adminId||Boolean(entering)} onClick={()=>void enterAsAdmin(c)}>{entering===c.id?'Entrando…':'Entrar como administrador'}</button>{!c.adminId&&<small>Sin administrador activo en el club.</small>}<button className="platform-preview" onClick={()=>setClubFocus(c.id)}>Abrir gestión del club</button></footer></article>)}</div></div>
 <div className="economy-card"><h3>Control de cobros</h3><p>Los cobros por club, pendientes y liquidaciones estarán disponibles cuando se conecte la plataforma de pago.</p><button disabled>Cobros por club</button> <button disabled>Liquidaciones</button></div>
 </>}
 </section>;
}