import { useEffect, useState, type CSSProperties } from 'react';
import { ArrowRight, Check, CreditCard, ShieldCheck } from 'lucide-react';
import { categoryNames, classifyBirth } from './enrollment';
import { money } from './EnrollmentPanel';
import './enrollment.css';

async function publicRequest(body?:unknown,slug?:string){const response=await fetch('/api/clubs?section=enrollment&public=1'+(slug?'&club='+encodeURIComponent(slug):''),{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'No se pudo completar la operación.');return data}
export default function PublicEnrollment(){
  const payment=location.pathname==='/pago';const token=location.hash.slice(1);
  const slug=decodeURIComponent(location.pathname.split('/')[2]||'');
  const [data,setData]=useState<any>(null),[campaignId,setCampaignId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[paid,setPaid]=useState(false);
  const [draft,setDraft]=useState({child_name:'',birth_date:'',guardian_name:'',email:'',phone:'',mode:'full',consent:false});
  useEffect(()=>{let active=true;publicRequest(payment?{action:'payment-info',token}:undefined,slug).then(result=>{if(active){setData(result);setCampaignId(result.campaigns?.[0]?.id||'');setPaid(Boolean(result.due?.paid_at))}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[payment,slug,token]);
  const campaign=data?.campaigns?.find((c:any)=>c.id===campaignId);
  const category=campaign?classifyBirth(draft.birth_date,campaign.categories):null;
  const pay=async()=>{setBusy(true);setError('');try{const result=await publicRequest({action:'pay',token});if(result.paid)setPaid(true);else location.assign(result.url)}catch(e){setError(e instanceof Error?e.message:'No se pudo abrir el pago.')}finally{setBusy(false)}};
  return <main className="public-enrollment" style={{'--enrollment-brand':data?.club?.color_principal||'#0b2344'} as CSSProperties}>
    <header className="public-enrollment-brand">{data?.club?.logo?<img src={data.club.logo} alt=""/>:<ShieldCheck size={38}/>}<div><strong>{data?.club?.nombre||data?.due?.nombre||'Convo'}</strong><span>{payment?'PAGO DE CUOTA':'INSCRIPCIÓN DE TEMPORADA'}</span></div></header>
    <div className="public-enrollment-body">
    {error&&<p role="alert" className="enrollment-alert">{error}</p>}
    {!data&&!error&&<p role="status">Cargando…</p>}
    {payment&&data&&<section className="enrollment-card public-payment"><span className="enrollment-large-icon">{paid?<Check size={30}/>:<CreditCard size={30}/>}</span><h1>{paid?'Cuota abonada':'Tu cuota, en un paso'}</h1><p>{paid?'El pago está confirmado. Recibirás el justificante por correo.':'Paga de forma segura, sin crear una cuenta.'}</p><strong className="public-payment-amount">{money(data.due.amount_cents)}</strong><p>Cuota {data.due.ordinal} · Vencimiento {data.due.due_date.slice(0,10)}</p>{!paid&&<button className="enrollment-primary" disabled={busy} onClick={()=>void pay()}>{busy?'Comprobando pago…':'Pagar / comprobar pago'} <ArrowRight size={18}/></button>}</section>}
    {!payment&&data&&(!data.ready||!campaign)?<section className="enrollment-card public-payment"><ShieldCheck size={36}/><h1>Inscripciones todavía no disponibles</h1><p>El club está preparando la temporada. Vuelve a este enlace cuando se anuncie la apertura.</p></section>:!payment&&campaign&&<><div className="public-enrollment-intro"><span className="admin-kicker">{campaign.name}</span><h1>El próximo equipo<br/>empieza contigo.</h1><p>Completa la inscripción y realiza el pago. El club asignará el equipo después.</p></div><form className="enrollment-card enrollment-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const result=await publicRequest({action:'register',campaign:campaignId,...draft});location.assign(`/pago#${result.token}`)}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setBusy(false)}}}>
      {data.campaigns.length>1&&<label>Temporada<select value={campaignId} onChange={e=>{setCampaignId(e.target.value);setDraft({...draft,consent:false})}}>{data.campaigns.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
      <h2><span>01</span> Datos del jugador</h2><div className="enrollment-form-grid"><label>Nombre y apellidos<input autoComplete="off" required minLength={3} maxLength={120} value={draft.child_name} onChange={e=>setDraft({...draft,child_name:e.target.value})}/></label><label>Fecha de nacimiento<input type="date" required max={new Date().toISOString().slice(0,10)} value={draft.birth_date} onChange={e=>setDraft({...draft,birth_date:e.target.value})}/></label></div>{draft.birth_date&&<p className={category?'enrollment-notice':'enrollment-alert'}>{category?`Categoría: ${categoryNames[category]}. El equipo lo asignará el club.`:'La fecha no corresponde a las categorías abiertas.'}</p>}
      <h2><span>02</span> Representante del menor</h2><label>Nombre y apellidos del padre, madre o tutor<input autoComplete="name" required minLength={3} maxLength={120} value={draft.guardian_name} onChange={e=>setDraft({...draft,guardian_name:e.target.value})}/></label><div className="enrollment-form-grid"><label>Correo para los recibos<input type="email" autoComplete="email" required maxLength={200} value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Teléfono de contacto<input type="tel" autoComplete="tel" required maxLength={25} value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label></div>
      <h2><span>03</span> Forma de pago</h2><div className="public-payment-options"><label><input type="radio" name="payment-mode" checked={draft.mode==='full'} onChange={()=>setDraft({...draft,mode:'full'})}/><span><strong>Pago completo</strong><small>{money(campaign.total_cents)} al inscribirte</small></span></label>{campaign.parts.length>1&&<label><input type="radio" name="payment-mode" checked={draft.mode==='parts'} onChange={()=>setDraft({...draft,mode:'parts'})}/><span><strong>{campaign.parts.length} plazos</strong><small>{money(campaign.parts[0].amount)} al inscribirte</small></span></label>}</div>{draft.mode==='parts'&&<div className="public-installments">{campaign.parts.map((p:any,i:number)=><div key={i}><span>{i===0?'Hoy, al inscribirte':p.date}</span><strong>{money(p.amount)}</strong></div>)}<p>Recibirás por correo los enlaces de los siguientes plazos. No son cargos automáticos.</p></div>}
      <details className="public-terms"><summary>Condiciones e información sobre tus datos</summary><p>{campaign.terms}</p></details><label className="public-consent"><input type="checkbox" required checked={draft.consent} onChange={e=>setDraft({...draft,consent:e.target.checked})}/><span>Confirmo que soy el representante del menor y he leído y acepto las condiciones de inscripción y la información sobre los datos.</span></label><footer><span>Total de la inscripción <strong>{money(campaign.total_cents)}</strong></span><button className="enrollment-primary" disabled={busy||!category||!draft.consent}>{busy?'Guardando…':'Continuar al pago'} <ArrowRight size={18}/></button></footer><p>La inscripción queda confirmada cuando se verifica el primer pago.</p>
    </form></>}
    </div><footer className="public-enrollment-footer">Gestionado con Convo · Sin cuentas para familias</footer>
  </main>;
}
