import { useState } from 'react';
import { ArrowDown, ArrowUp, Check, Pencil, Plus, RefreshCw, Sparkles, Trash2, X } from 'lucide-react';
import { clubApi } from './api';
import { TrainingBoard } from './TrainingBoard';
import { COLLECTIVE_OBJECTIVES, INDIVIDUAL_OBJECTIVES, TRAINING_MATERIALS, type TrainingAIContext, type TrainingAIExercise, type TrainingAISession } from './trainingAI';

interface Props { eventId:string; teamName:string; category:string; format:'F8'|'F11'; initialPlayers:number; initialGoalkeepers:number; initialDuration:number; current?:TrainingAISession|null; onApply:(session:TrainingAISession)=>void; }
const lines=(value:string)=>value.split('\n').map(item=>item.trim()).filter(Boolean);
const joined=(value:string[])=>value.join('\n');
const blankExercise=(players:number,order:number):TrainingAIExercise=>({id:`manual-${Date.now()}`,order,block:'Tarea adicional',name:'Nuevo ejercicio',duration:10,objective:'Objetivo por definir',players,space:'',material:[],organization:'',development:'',instructions:[],variants:[],coachingPoints:[],board:[],actions:[]});

export function TrainingAIWizard({eventId,teamName,category,format,initialPlayers,initialGoalkeepers,initialDuration,current,onApply}:Props){
 const [open,setOpen]=useState(false),[step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[instruction,setInstruction]=useState(''),[editing,setEditing]=useState<string|null>(null);
 const [result,setResult]=useState<TrainingAISession|null>(current||null);
 const [context,setContext]=useState<TrainingAIContext>({players:Math.max(1,initialPlayers),goalkeepers:Math.max(0,initialGoalkeepers),duration:initialDuration||90,level:'medio',mode:'individual',objectives:[],material:['Balones','Conos pequeños','Petos'],fieldSize:'Medio campo',intensity:'media',observations:''});
 const objectives=context.mode==='individual'?INDIVIDUAL_OBJECTIVES:COLLECTIVE_OBJECTIVES;
 const call=async(action:'session'|'exercise'|'adapt',exercise?:TrainingAIExercise)=>{setBusy(true);setError('');try{const response=await clubApi.generateTraining({eventId,action,context,category,format,currentSession:result||undefined,exercise,instruction});setResult(response.session);setStep(5);setInstruction('');}catch(e){setError(e instanceof Error?e.message:'No se pudo generar la sesión.');}finally{setBusy(false)}};
 const updateExercise=(id:string,change:Partial<TrainingAIExercise>)=>setResult(value=>value?{...value,exercises:value.exercises.map(item=>item.id===id?{...item,...change}:item)}:value);
 const move=(index:number,direction:-1|1)=>setResult(value=>{if(!value)return value;const target=index+direction;if(target<0||target>=value.exercises.length)return value;const exercises=[...value.exercises];[exercises[index],exercises[target]]=[exercises[target],exercises[index]];return{...value,exercises:exercises.map((item,i)=>({...item,order:i+1}))}});
 if(!open)return <section className="training-ai-entry"><div><span><Sparkles size={18}/> IA · DESARROLLO PRIVADO</span><h3>Generar entrenamiento con IA</h3><p>Crea una sesión adaptada a este equipo y después revísala antes de guardarla.</p></div><button type="button" onClick={()=>setOpen(true)}><Sparkles size={17}/> Empezar</button></section>;
 return <section className="training-ai-wizard">
  <header><div><span className="eyebrow">GENERADOR IA · {teamName}</span><h3>{step<5?`Paso ${step} de 4`:result?.title||'Entrenamiento generado'}</h3></div><button type="button" aria-label="Cerrar generador" onClick={()=>setOpen(false)}><X size={19}/></button></header>
  {step===1&&<div className="training-ai-step"><h4>Contexto de la sesión</h4><div className="training-ai-context-summary"><strong>{teamName}</strong><span>{category} · {format}</span></div><div className="training-ai-grid"><label>Jugadores<input type="number" min="1" max="40" value={context.players} onChange={e=>setContext({...context,players:Number(e.target.value)})}/></label><label>Porteros<input type="number" min="0" max="6" value={context.goalkeepers} onChange={e=>setContext({...context,goalkeepers:Number(e.target.value)})}/></label><label>Duración total<input type="number" min="20" max="180" step="5" value={context.duration} onChange={e=>setContext({...context,duration:Number(e.target.value)})}/></label><label>Nivel<select value={context.level} onChange={e=>setContext({...context,level:e.target.value as TrainingAIContext['level']})}><option value="iniciacion">Iniciación</option><option value="medio">Medio</option><option value="avanzado">Avanzado</option></select></label></div></div>}
  {step===2&&<div className="training-ai-step"><h4>Tipo de entrenamiento</h4><div className="training-ai-mode"><button type="button" className={context.mode==='individual'?'active':''} onClick={()=>setContext({...context,mode:'individual',objectives:[]})}><strong>Desarrollo individual</strong><span>Técnica y decisiones del jugador</span></button><button type="button" className={context.mode==='collective'?'active':''} onClick={()=>setContext({...context,mode:'collective',objectives:[]})}><strong>Rendimiento colectivo</strong><span>Principios y coordinación del equipo</span></button></div><div className="training-ai-chips">{objectives.map(objective=><button type="button" className={context.objectives.includes(objective)?'active':''} key={objective} onClick={()=>setContext({...context,objectives:context.objectives.includes(objective)?context.objectives.filter(item=>item!==objective):[...context.objectives,objective]})}>{context.objectives.includes(objective)&&<Check size={13}/>} {objective}</button>)}</div></div>}
  {step===3&&<div className="training-ai-step"><h4>Condiciones</h4><span className="training-ai-label">Material disponible</span><div className="training-ai-chips compact">{TRAINING_MATERIALS.map(material=><button type="button" className={context.material.includes(material)?'active':''} key={material} onClick={()=>setContext({...context,material:context.material.includes(material)?context.material.filter(item=>item!==material):[...context.material,material]})}>{material}</button>)}</div><div className="training-ai-grid"><label>Espacio aproximado<input value={context.fieldSize} maxLength={120} onChange={e=>setContext({...context,fieldSize:e.target.value})}/></label><label>Intensidad<select value={context.intensity} onChange={e=>setContext({...context,intensity:e.target.value as TrainingAIContext['intensity']})}><option value="baja">Baja</option><option value="media">Media</option><option value="alta">Alta</option></select></label></div><label>Observaciones<textarea rows={4} maxLength={1000} value={context.observations} onChange={e=>setContext({...context,observations:e.target.value})} placeholder="Ej. El rival presiona arriba y quiero trabajar la salida de balón."/></label></div>}
  {step===4&&<div className="training-ai-step training-ai-confirm"><Sparkles size={34}/><h4>Todo listo para generar</h4><p>{context.duration} min · {context.players} jugadores · {context.objectives.join(' · ')}</p><button type="button" disabled={busy} onClick={()=>void call('session')}><Sparkles size={17}/> {busy?'Preparando tu sesión…':'Generar entrenamiento con IA'}</button></div>}
  {step===5&&result&&<div className="training-ai-result"><div className="training-ai-result-summary"><label>Título<input value={result.title} onChange={e=>setResult({...result,title:e.target.value})}/></label><label>Resumen<textarea rows={3} value={result.summary} onChange={e=>setResult({...result,summary:e.target.value})}/></label><label>Material total<input value={result.totalMaterial.join(', ')} onChange={e=>setResult({...result,totalMaterial:e.target.value.split(',').map(item=>item.trim()).filter(Boolean)})}/></label><div>{result.objectives.map(item=><span key={item}>{item}</span>)}</div><small>{result.exercises.reduce((sum,item)=>sum+item.duration,0)} min · {result.players} jugadores · {result.category} · {result.format}</small></div>
   <div className="training-ai-exercises">{result.exercises.map((exercise,index)=><article key={exercise.id}><header><span>{index+1}</span><div><em>{exercise.block}</em><h4>{exercise.name}</h4><small>{exercise.duration} min · {exercise.objective}</small></div><div><button type="button" aria-label="Subir" disabled={index===0} onClick={()=>move(index,-1)}><ArrowUp size={14}/></button><button type="button" aria-label="Bajar" disabled={index===result.exercises.length-1} onClick={()=>move(index,1)}><ArrowDown size={14}/></button></div></header>
    {editing===exercise.id?<div className="training-ai-editor"><div className="training-ai-grid"><label>Bloque<input value={exercise.block} onChange={e=>updateExercise(exercise.id,{block:e.target.value})}/></label><label>Nombre<input value={exercise.name} onChange={e=>updateExercise(exercise.id,{name:e.target.value})}/></label><label>Duración<input type="number" min="3" max="90" value={exercise.duration} onChange={e=>updateExercise(exercise.id,{duration:Number(e.target.value)})}/></label><label>Objetivo<input value={exercise.objective} onChange={e=>updateExercise(exercise.id,{objective:e.target.value})}/></label><label>Espacio<input value={exercise.space} onChange={e=>updateExercise(exercise.id,{space:e.target.value})}/></label><label>Material<input value={exercise.material.join(', ')} onChange={e=>updateExercise(exercise.id,{material:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)})}/></label></div><label>Organización<textarea rows={3} value={exercise.organization} onChange={e=>updateExercise(exercise.id,{organization:e.target.value})}/></label><label>Desarrollo<textarea rows={4} value={exercise.development} onChange={e=>updateExercise(exercise.id,{development:e.target.value})}/></label><label>Consignas, una por línea<textarea rows={3} value={joined(exercise.instructions)} onChange={e=>updateExercise(exercise.id,{instructions:lines(e.target.value)})}/></label><label>Variantes, una por línea<textarea rows={3} value={joined(exercise.variants)} onChange={e=>updateExercise(exercise.id,{variants:lines(e.target.value)})}/></label><label>Puntos del entrenador, uno por línea<textarea rows={3} value={joined(exercise.coachingPoints)} onChange={e=>updateExercise(exercise.id,{coachingPoints:lines(e.target.value)})}/></label><button type="button" onClick={()=>setEditing(null)}><Check size={15}/> Terminar edición</button></div>:<div className="training-ai-exercise-detail"><p><strong>Organización</strong>{exercise.organization}</p><p><strong>Desarrollo</strong>{exercise.development}</p><p><strong>Material y espacio</strong>{exercise.material.join(', ')||'Sin material'} · {exercise.space||'Espacio libre'}</p>{exercise.board.length>0?<><p><strong>Pizarra inicial</strong>Podrás mover fichas y corregir acciones al aplicar la sesión.</p><TrainingBoard pieces={exercise.board} actions={exercise.actions} compact label={`Pizarra de ${exercise.name}`}/></>:null}{exercise.instructions.length>0&&<ul>{exercise.instructions.map(item=><li key={item}>{item}</li>)}</ul>}</div>}
    <footer><button type="button" onClick={()=>setEditing(exercise.id)}><Pencil size={14}/> Editar</button><button type="button" disabled={busy} onClick={()=>void call('exercise',exercise)}><Sparkles size={14}/> Regenerar</button><button type="button" className="danger" onClick={()=>setResult({...result,exercises:result.exercises.filter(item=>item.id!==exercise.id)})}><Trash2 size={14}/> Eliminar</button></footer></article>)}</div>
   <button type="button" className="training-ai-add" onClick={()=>setResult({...result,exercises:[...result.exercises,blankExercise(context.players,result.exercises.length+1)]})}><Plus size={15}/> Añadir ejercicio manual</button>
   <div className="training-ai-adapt"><label>¿Qué quieres cambiar?<input value={instruction} maxLength={600} onChange={e=>setInstruction(e.target.value)} placeholder="Ej. Finalmente somos 7 y no tengo miniporterías"/></label><button type="button" disabled={busy||!instruction.trim()} onClick={()=>void call('adapt')}><RefreshCw size={15}/> {busy?'Adaptando…':'Adaptar entrenamiento'}</button></div>
   <div className="training-ai-final-actions"><button type="button" onClick={()=>{setStep(1);setResult(null)}}>Empezar de nuevo</button><button type="button" className="primary-button" onClick={()=>{onApply({...result,totalDuration:result.exercises.reduce((sum,item)=>sum+item.duration,0)});setOpen(false)}}><Check size={16}/> Usar esta sesión</button></div>
  </div>}
  {error&&<p role="alert" className="training-ai-error">{error}</p>}
  {step<4&&<footer><button type="button" disabled={step===1} onClick={()=>setStep(value=>Math.max(1,value-1))}>Atrás</button><button type="button" disabled={step===2&&!context.objectives.length} onClick={()=>setStep(value=>Math.min(4,value+1))}>Continuar</button></footer>}
 </section>;
}
